-- MySQL Script generated by MySQL Workbench
-- Tue May  7 16:30:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema integrador_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `integrador_db` ;

-- -----------------------------------------------------
-- Schema integrador_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integrador_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `integrador_db` ;

-- -----------------------------------------------------
-- Table `integrador_db`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`categoria` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`categoria` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`producto` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`producto` (
  `id` INT(10) UNSIGNED NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(12,2) NULL DEFAULT NULL,
  `id_categoria` INT(10) UNSIGNED NULL DEFAULT NULL,
  `image_view` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `integrador_db`.`categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`venta` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`venta` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `monto_total` DECIMAL(12,2) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  `usuario_registro` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`detalle_venta` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_producto` INT(10) UNSIGNED NULL DEFAULT NULL,
  `id_venta` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_detalle_venta_venta_idx` (`id_venta` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `integrador_db`.`producto` (`id`),
  CONSTRAINT `fk_detalle_venta_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `integrador_db`.`venta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`perfil` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`perfil` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_nacimiento` DATETIME NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `ranking` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`galeria_fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`galeria_fotos` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`galeria_fotos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_view` BLOB NULL DEFAULT NULL,
  `id_perfil` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_perfil_idx` (`id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_galeria_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `integrador_db`.`perfil` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`tag` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`noticia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`noticia` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`noticia` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tag` INT(10) UNSIGNED NULL DEFAULT NULL,
  `titulo` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_publicacion` DATETIME NULL DEFAULT NULL,
  `comentario` VARCHAR(200) NULL DEFAULT NULL,
  `comentario_habilitado` VARCHAR(1) NULL DEFAULT NULL,
  `image_preview` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noticia_tag_idx` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `fk_noticia_tag`
    FOREIGN KEY (`id_tag`)
    REFERENCES `integrador_db`.`tag` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
